name: "docusaurus"
services:
    serve:
        build:
            context: .
            target: serve
        ports:
            - "52841:3000"
        environment:
            - NODE_ENV=production