version: "3"

services:
  docusaurus:
    container_name: docusaurus
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "52841:80"
    environment:
      - NODE_ENV=production